module.exports = {
    login: require("./login"),
    logout: require("./logout"),
    register: require("./register"),
    check: require("./check"),
    getskill: require("./getskill"),
    addDetailPreDek: require("./addDetailPreDek"),
    uploadfile: require("./uploadfile"),
    addDetailWork: require("./addDetailWork"),
    createWork: require("./createWork"),
    getWorkList: require("./getWorkList"),
    matchPredek: require("./matchPredek"),
    Invite: require("./Invite"),
    workInterested: require("./workInterested"),
    getpredekdata: require("./getpredekdata"),
    imageCupload: require("./imageCupload"),
    selectList: require("./selectList"),
    getworkdata: require("./getworkdata"),
    changepassword: require("./changepassword"),
    changefname: require("./changefname"),
    changelname: require("./changelname"),
    changePre: require("./changePre"),
    Partnerlist: require("./Partnerlist"),
};